version: "3"
services:
  mysqldb:
    image: mysql
    ports:
      - "8081:3306"
    env_file:
      - staging.env
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1
    volumes:
      - db-data:/var/lib/mysql
  docker-assignment:
    image: 256048785424.dkr.ecr.ap-south-1.amazonaws.com/docker_assignment
    build: ./
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
       mysqldb: 
          condition: service_healthy
volumes:
  db-data:
